apiVersion: kro.run/v1alpha1
kind: QueueBackedService
metadata:
  name: {{ .Values.name | default "orders" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name | default "orders" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
    environment: {{ .Values.environment }}
spec:
  name: {{ .Values.name | default "orders" }}
  environment: {{ .Values.environment }}
  replicas: {{ .Values.replicas | default 1 }}
  messageRetentionPeriod: {{ .Values.retentionPeriod | default "86400" | quote }}
  image: {{ required "A container image must be specified in .Values.image" .Values.image }}
